#!/usr/bin/env bash
#configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get install -y nginx

#custom header
sudo sed -i "s/listen \[::\]:80 default_server;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default

sudo service nginx restart
